package com.example.olympus

object EjerciciosData {
    fun getEjercicios(): List<Ejercicio> = listOf(
        // PECHO
        Ejercicio(1, "Press de Banca", android.R.drawable.ic_menu_gallery),
        Ejercicio(2, "Press Inclinado", android.R.drawable.ic_menu_gallery),
        Ejercicio(3, "Press Declinado", android.R.drawable.ic_menu_gallery),
        Ejercicio(4, "Press con Mancuernas", android.R.drawable.ic_menu_gallery),
        Ejercicio(5, "Aperturas", android.R.drawable.ic_menu_gallery),
        Ejercicio(6, "Aperturas Inclinadas", android.R.drawable.ic_menu_gallery),
        Ejercicio(7, "Fondos en Paralelas", android.R.drawable.ic_menu_gallery),
        Ejercicio(8, "Cruce de Poleas", android.R.drawable.ic_menu_gallery),
        Ejercicio(9, "Pullover", android.R.drawable.ic_menu_gallery),
        Ejercicio(10, "Press Máquina", android.R.drawable.ic_menu_gallery),
        Ejercicio(11, "Flexiones", android.R.drawable.ic_menu_gallery),
        Ejercicio(12, "Flexiones Declinadas", android.R.drawable.ic_menu_gallery),
        Ejercicio(13, "Flexiones con Palmada", android.R.drawable.ic_menu_gallery),
        Ejercicio(14, "Press Barra Smith", android.R.drawable.ic_menu_gallery),
        Ejercicio(15, "Peck Deck", android.R.drawable.ic_menu_gallery),

        // ESPALDA
        Ejercicio(16, "Peso Muerto", android.R.drawable.ic_menu_gallery),
        Ejercicio(17, "Dominadas", android.R.drawable.ic_menu_gallery),
        Ejercicio(18, "Remo con Barra", android.R.drawable.ic_menu_gallery),
        Ejercicio(19, "Remo con Mancuerna", android.R.drawable.ic_menu_gallery),
        Ejercicio(20, "Jalón al Pecho", android.R.drawable.ic_menu_gallery),
        Ejercicio(21, "Jalón Tras Nuca", android.R.drawable.ic_menu_gallery),
        Ejercicio(22, "Remo en Polea", android.R.drawable.ic_menu_gallery),
        Ejercicio(23, "Pull Over Polea", android.R.drawable.ic_menu_gallery),
        Ejercicio(24, "Peso Muerto Rumano", android.R.drawable.ic_menu_gallery),
        Ejercicio(25, "Hiperextensiones", android.R.drawable.ic_menu_gallery),
        Ejercicio(26, "Remo en T", android.R.drawable.ic_menu_gallery),
        Ejercicio(27, "Face Pull", android.R.drawable.ic_menu_gallery),
        Ejercicio(28, "Remo Invertido", android.R.drawable.ic_menu_gallery),
        Ejercicio(29, "Encogimientos Barra", android.R.drawable.ic_menu_gallery),
        Ejercicio(30, "Encogimientos Mancuernas", android.R.drawable.ic_menu_gallery),

        // PIERNAS
        Ejercicio(31, "Sentadilla", android.R.drawable.ic_menu_gallery),
        Ejercicio(32, "Sentadilla Frontal", android.R.drawable.ic_menu_gallery),
        Ejercicio(33, "Sentadilla Búlgara", android.R.drawable.ic_menu_gallery),
        Ejercicio(34, "Prensa", android.R.drawable.ic_menu_gallery),
        Ejercicio(35, "Zancadas Barra", android.R.drawable.ic_menu_gallery),
        Ejercicio(36, "Zancadas Mancuernas", android.R.drawable.ic_menu_gallery),
        Ejercicio(37, "Extensión Cuádriceps", android.R.drawable.ic_menu_gallery),
        Ejercicio(38, "Curl Femoral", android.R.drawable.ic_menu_gallery),
        Ejercicio(39, "Curl Femoral Sentado", android.R.drawable.ic_menu_gallery),
        Ejercicio(40, "Peso Muerto Piernas Rígidas", android.R.drawable.ic_menu_gallery),
        Ejercicio(41, "Hip Thrust", android.R.drawable.ic_menu_gallery),
        Ejercicio(42, "Gemelos Parado", android.R.drawable.ic_menu_gallery),
        Ejercicio(43, "Gemelos Sentado", android.R.drawable.ic_menu_gallery),
        Ejercicio(44, "Hack Squat", android.R.drawable.ic_menu_gallery),
        Ejercicio(45, "Step Ups", android.R.drawable.ic_menu_gallery),
        Ejercicio(46, "Abducción Cadera", android.R.drawable.ic_menu_gallery),
        Ejercicio(47, "Aducción Cadera", android.R.drawable.ic_menu_gallery),
        Ejercicio(48, "Sentadilla Sumo", android.R.drawable.ic_menu_gallery),
        Ejercicio(49, "Pistol Squat", android.R.drawable.ic_menu_gallery),
        Ejercicio(50, "Box Jumps", android.R.drawable.ic_menu_gallery),

        // HOMBROS
        Ejercicio(51, "Press Militar", android.R.drawable.ic_menu_gallery),
        Ejercicio(52, "Press Arnold", android.R.drawable.ic_menu_gallery),
        Ejercicio(53, "Elevaciones Laterales", android.R.drawable.ic_menu_gallery),
        Ejercicio(54, "Elevaciones Frontales", android.R.drawable.ic_menu_gallery),
        Ejercicio(55, "Pájaros", android.R.drawable.ic_menu_gallery),
        Ejercicio(56, "Press Mancuernas", android.R.drawable.ic_menu_gallery),
        Ejercicio(57, "Remo al Cuello", android.R.drawable.ic_menu_gallery),
        Ejercicio(58, "Elevaciones Polea", android.R.drawable.ic_menu_gallery),
        Ejercicio(59, "Press Tras Nuca", android.R.drawable.ic_menu_gallery),
        Ejercicio(60, "Face Pull Deltoide", android.R.drawable.ic_menu_gallery),
        Ejercicio(61, "Elevaciones Cruz", android.R.drawable.ic_menu_gallery),
        Ejercicio(62, "Press Landmine", android.R.drawable.ic_menu_gallery),
        Ejercicio(63, "Elevaciones Disco", android.R.drawable.ic_menu_gallery),
        Ejercicio(64, "Press Kettlebell", android.R.drawable.ic_menu_gallery),
        Ejercicio(65, "Handstand Push Ups", android.R.drawable.ic_menu_gallery),

        // BRAZOS
        Ejercicio(66, "Curl Barra", android.R.drawable.ic_menu_gallery),
        Ejercicio(67, "Curl Mancuernas", android.R.drawable.ic_menu_gallery),
        Ejercicio(68, "Curl Martillo", android.R.drawable.ic_menu_gallery),
        Ejercicio(69, "Curl Predicador", android.R.drawable.ic_menu_gallery),
        Ejercicio(70, "Curl Concentrado", android.R.drawable.ic_menu_gallery),
        Ejercicio(71, "Press Francés", android.R.drawable.ic_menu_gallery),
        Ejercicio(72, "Extensiones Tríceps", android.R.drawable.ic_menu_gallery),
        Ejercicio(73, "Fondos Tríceps", android.R.drawable.ic_menu_gallery),
        Ejercicio(74, "Patada Tríceps", android.R.drawable.ic_menu_gallery),
        Ejercicio(75, "Press Cerrado", android.R.drawable.ic_menu_gallery),
        Ejercicio(76, "Curl Polea Baja", android.R.drawable.ic_menu_gallery),
        Ejercicio(77, "Curl Polea Alta", android.R.drawable.ic_menu_gallery),
        Ejercicio(78, "Extensión Polea", android.R.drawable.ic_menu_gallery),
        Ejercicio(79, "Curl 21s", android.R.drawable.ic_menu_gallery),
        Ejercicio(80, "Curl Invertido", android.R.drawable.ic_menu_gallery),
        Ejercicio(81, "Tríceps Cuerda", android.R.drawable.ic_menu_gallery),
        Ejercicio(82, "Curl Spider", android.R.drawable.ic_menu_gallery),
        Ejercicio(83, "Extensión Overhead", android.R.drawable.ic_menu_gallery),
        Ejercicio(84, "Curl Zottman", android.R.drawable.ic_menu_gallery),
        Ejercicio(85, "Diamond Push Ups", android.R.drawable.ic_menu_gallery),

        // ABDOMEN
        Ejercicio(86, "Crunch", android.R.drawable.ic_menu_gallery),
        Ejercicio(87, "Plancha", android.R.drawable.ic_menu_gallery),
        Ejercicio(88, "Elevaciones Pierna", android.R.drawable.ic_menu_gallery),
        Ejercicio(89, "Bicicleta", android.R.drawable.ic_menu_gallery),
        Ejercicio(90, "Russian Twist", android.R.drawable.ic_menu_gallery),
        Ejercicio(91, "Mountain Climbers", android.R.drawable.ic_menu_gallery),
        Ejercicio(92, "Ab Wheel", android.R.drawable.ic_menu_gallery),
        Ejercicio(93, "V-Ups", android.R.drawable.ic_menu_gallery),
        Ejercicio(94, "Plancha Lateral", android.R.drawable.ic_menu_gallery),
        Ejercicio(95, "Dead Bug", android.R.drawable.ic_menu_gallery),

        // FUNCIONALES
        Ejercicio(96, "Burpees", android.R.drawable.ic_menu_gallery),
        Ejercicio(97, "Thrusters", android.R.drawable.ic_menu_gallery),
        Ejercicio(98, "Wall Balls", android.R.drawable.ic_menu_gallery),
        Ejercicio(99, "Kettlebell Swing", android.R.drawable.ic_menu_gallery),
        Ejercicio(100, "Turkish Get Up", android.R.drawable.ic_menu_gallery),
        Ejercicio(101, "Clean and Jerk", android.R.drawable.ic_menu_gallery),
        Ejercicio(102, "Snatch", android.R.drawable.ic_menu_gallery),
        Ejercicio(103, "Power Clean", android.R.drawable.ic_menu_gallery),
        Ejercicio(104, "Box Jumps", android.R.drawable.ic_menu_gallery),
        Ejercicio(105, "Battle Ropes", android.R.drawable.ic_menu_gallery),
        Ejercicio(106, "Farmers Walk", android.R.drawable.ic_menu_gallery),
        Ejercicio(107, "Sled Push", android.R.drawable.ic_menu_gallery),
        Ejercicio(108, "Tire Flip", android.R.drawable.ic_menu_gallery),
        Ejercicio(109, "Rope Climbs", android.R.drawable.ic_menu_gallery),
        Ejercicio(110, "Double Unders", android.R.drawable.ic_menu_gallery)
    )
}
