package com.example.olympus

// Base de datos local de ejercicios de gymnasio organizados por grupo muscular

object EjerciciosData {
    fun getEjercicios(): List<Ejercicio> = listOf(
        // PECHO
        Ejercicio(1, "Press de Banca", R.drawable.press_banca),
        Ejercicio(2, "Press Inclinado", R.drawable.press_inclinado),
        Ejercicio(3, "Press Declinado", R.drawable.press_declinado),
        Ejercicio(4, "Press con Mancuernas", R.drawable.press_con_mancuernas),
        Ejercicio(5, "Aperturas", R.drawable.aperturas),
        Ejercicio(6, "Aperturas Inclinadas", R.drawable.aperturas_inclinadas),
        Ejercicio(7, "Fondos en Paralelas", R.drawable.fondos_en_paralelas),
        Ejercicio(8, "Cruce de Poleas", R.drawable.cruce_de_poleas),
        Ejercicio(9, "Pullover", R.drawable.pullover),
        Ejercicio(10, "Press Máquina", R.drawable.press_maquina),
        Ejercicio(11, "Flexiones", R.drawable.flexiones),
        Ejercicio(12, "Flexiones Declinadas", R.drawable.flexiones_declinadas),
        Ejercicio(13, "Flexiones con Palmada", R.drawable.flexiones_con_palmadas),
        Ejercicio(14, "Press Barra Smith", R.drawable.press_barra_smith),
        Ejercicio(15, "Peck Deck", R.drawable.peck_deck),

        // ESPALDA
        Ejercicio(16, "Peso Muerto", R.drawable.peso_muerto),
        Ejercicio(17, "Dominadas", R.drawable.dominadas),
        Ejercicio(18, "Remo con Barra", R.drawable.remo_con_barra),
        Ejercicio(19, "Remo con Mancuerna", R.drawable.remo_con_mancuerna),
        Ejercicio(20, "Jalón al Pecho", R.drawable.jalon_al_pecho),
        Ejercicio(21, "Jalón Tras Nuca", R.drawable.jalon_tras_nuca),
        Ejercicio(22, "Remo en Polea", R.drawable.remo_con_polea),
        Ejercicio(23, "Pull Over Polea", R.drawable.pull_over_polea),
        Ejercicio(24, "Peso Muerto Rumano", R.drawable.peso_muerto_rumano),
        Ejercicio(25, "Hiperextensiones", R.drawable.hiperextensiones),
        Ejercicio(26, "Remo en T", R.drawable.remo_en_t),
        Ejercicio(27, "Face Pull", R.drawable.face_pull),
        Ejercicio(28, "Remo Invertido", R.drawable.remo_invertido),
        Ejercicio(29, "Encogimientos Barra", R.drawable.encogimientos_barra),
        Ejercicio(30, "Encogimientos Mancuernas", R.drawable.encogimientos_mancuernas),

        // PIERNAS
        Ejercicio(31, "Sentadilla", R.drawable.sentadilla),
        Ejercicio(32, "Sentadilla Frontal", R.drawable.sentadilla_frontal),
        Ejercicio(33, "Sentadilla Búlgara", R.drawable.sentadilla_bulgara),
        Ejercicio(34, "Prensa", R.drawable.prensa),
        Ejercicio(35, "Zancadas Barra", R.drawable.zancadas_barra),
        Ejercicio(36, "Zancadas Mancuernas", R.drawable.zancadas_con_mancuernas),
        Ejercicio(37, "Extensión Cuádriceps", R.drawable.extension_cuadriceps),
        Ejercicio(38, "Curl Femoral", R.drawable.curl_femoral),
        Ejercicio(39, "Curl Femoral Sentado", R.drawable.curl_femoral_sentado),
        Ejercicio(40, "Peso Muerto Piernas Rígidas", R.drawable.peso_muerto_piernas_rigidas),
        Ejercicio(41, "Hip Thrust", R.drawable.sentadilla),
        Ejercicio(42, "Gemelos Parado", R.drawable.gemelos_parado),
        Ejercicio(43, "Gemelos Sentado", R.drawable.gemelos_sentado),
        Ejercicio(44, "Hack Squat", R.drawable.hack_squat),
        Ejercicio(45, "Step Ups", R.drawable.step_ups),
        Ejercicio(46, "Abducción Cadera", R.drawable.abduccion_de_cadera),
        Ejercicio(47, "Aducción Cadera", R.drawable.aduccion_de_cadera),
        Ejercicio(48, "Sentadilla Sumo", R.drawable.sentadilla),
        Ejercicio(49, "Pistol Squat", R.drawable.pistol_squat),
        Ejercicio(50, "Box Jumps", R.drawable.box_jumps),

        // HOMBROS
        Ejercicio(51, "Press Militar", R.drawable.press_militar),
        Ejercicio(52, "Press Arnold", R.drawable.press_arnold),
        Ejercicio(53, "Elevaciones Laterales", R.drawable.elevaciones_laterales),
        Ejercicio(54, "Elevaciones Frontales", R.drawable.elevaciones_frontales),
        Ejercicio(55, "Pájaros", R.drawable.pajaros),
        Ejercicio(56, "Press Mancuernas", R.drawable.press_mancuernas),
        Ejercicio(57, "Remo al Cuello", R.drawable.remo_al_cuello),
        Ejercicio(58, "Elevaciones Polea", R.drawable.elevaciones_polea),
        Ejercicio(59, "Press Tras Nuca", R.drawable.press_tras_nuca),
        Ejercicio(60, "Face Pull Deltoide", R.drawable.face_pull_deltoide),
        Ejercicio(61, "Elevaciones Cruz", R.drawable.elevaciones_cruzadas),
        Ejercicio(62, "Press Landmine", R.drawable.press_landmine),
        Ejercicio(63, "Elevaciones Disco", R.drawable.elevaciones_disco),
        Ejercicio(64, "Press Kettlebell", R.drawable.press_kettlebell),
        Ejercicio(65, "Handstand Push Ups", R.drawable.handstand_push_ups),

        // BRAZOS
        Ejercicio(66, "Curl Barra", R.drawable.curl_barra),
        Ejercicio(67, "Curl Mancuernas", R.drawable.curl_mancuernas),
        Ejercicio(68, "Curl Martillo", R.drawable.curl_martillo),
        Ejercicio(69, "Curl Predicador", R.drawable.curl_predicador),
        Ejercicio(70, "Curl Concentrado", R.drawable.curl_concentrado),
        Ejercicio(71, "Press Francés", R.drawable.press_frances),
        Ejercicio(72, "Extensiones Tríceps", R.drawable.extensiones_triceps),
        Ejercicio(73, "Fondos Tríceps", R.drawable.fondos_triceps),
        Ejercicio(74, "Patada Tríceps", R.drawable.patada_triceps),
        Ejercicio(75, "Press Cerrado", R.drawable.press_cerrado),
        Ejercicio(76, "Curl Polea Baja", R.drawable.curl_polea_baja),
        Ejercicio(77, "Curl Polea Alta", R.drawable.curl_polea_alta),
        Ejercicio(78, "Extensión Polea", R.drawable.extension_polea),
        Ejercicio(79, "Curl 21s", R.drawable.curl_21s),
        Ejercicio(80, "Curl Invertido", R.drawable.curl_invertido),
        Ejercicio(81, "Tríceps Cuerda", R.drawable.tricep_cuerda),
        Ejercicio(82, "Curl Spider", R.drawable.curl_spider),
        Ejercicio(83, "Extensión Overhead", R.drawable.extension_overhead),
        Ejercicio(84, "Curl Zottman", R.drawable.curl_zottman),
        Ejercicio(85, "Diamond Push Ups", R.drawable.diamond_push_ups),

        // ABDOMEN
        Ejercicio(86, "Crunch", R.drawable.crunch),
        Ejercicio(87, "Plancha", R.drawable.plancha),
        Ejercicio(88, "Elevaciones Pierna", R.drawable.elevaciones_pierna),
        Ejercicio(89, "Bicicleta", R.drawable.bicicleta),
        Ejercicio(90, "Russian Twist", R.drawable.russian_twist),
        Ejercicio(91, "Mountain Climbers", R.drawable.mountain_climbers),
        Ejercicio(92, "Ab Wheel", R.drawable.ab_wheel),
        Ejercicio(93, "V-Ups", R.drawable.v_up),
        Ejercicio(94, "Plancha Lateral", R.drawable.plancha_lateral),
        Ejercicio(95, "Dead Bug", R.drawable.dead_bug),

        // FUNCIONALES
        Ejercicio(96, "Burpees", R.drawable.burpees),
        Ejercicio(97, "Thrusters", R.drawable.thruster),
        Ejercicio(98, "Wall Balls", R.drawable.wall_balls),
        Ejercicio(99, "Kettlebell Swing", R.drawable.kettlebell_swing),
        Ejercicio(100, "Turkish Get Up", R.drawable.turkish_get_up),
        Ejercicio(101, "Clean and Jerk", R.drawable.clean_and_jerk),
        Ejercicio(102, "Snatch", R.drawable.snatch),
        Ejercicio(103, "Power Clean", R.drawable.power_clean),
        Ejercicio(104, "Box Jumps", R.drawable.box_jumps),
        Ejercicio(105, "Battle Ropes", R.drawable.battle_ropes),
        Ejercicio(106, "Farmers Walk", R.drawable.farmers_walk),
        Ejercicio(107, "Sled Push", R.drawable.slep_push),
        Ejercicio(108, "Tire Flip", R.drawable.tire_flip),
        Ejercicio(109, "Rope Climbs", R.drawable.rope_climbs),
        Ejercicio(110, "Double Unders", R.drawable.double_unders)
    )
}