package com.example.olympus.data

import android.R
import com.example.olympus.Ejercicio

object EjerciciosData {
    fun getEjercicios(): List<Ejercicio> = listOf(
        // PECHO
        Ejercicio(1, "Press de Banca", R.drawable.ic_menu_gallery),
        Ejercicio(2, "Press Inclinado", R.drawable.ic_menu_gallery),
        Ejercicio(3, "Press Declinado", R.drawable.ic_menu_gallery),
        Ejercicio(4, "Press con Mancuernas", R.drawable.ic_menu_gallery),
        Ejercicio(5, "Aperturas", R.drawable.ic_menu_gallery),
        Ejercicio(6, "Aperturas Inclinadas", R.drawable.ic_menu_gallery),
        Ejercicio(7, "Fondos en Paralelas", R.drawable.ic_menu_gallery),
        Ejercicio(8, "Cruce de Poleas", R.drawable.ic_menu_gallery),
        Ejercicio(9, "Pullover", R.drawable.ic_menu_gallery),
        Ejercicio(10, "Press Máquina", R.drawable.ic_menu_gallery),
        Ejercicio(11, "Flexiones", R.drawable.ic_menu_gallery),
        Ejercicio(12, "Flexiones Declinadas", R.drawable.ic_menu_gallery),
        Ejercicio(13, "Flexiones con Palmada", R.drawable.ic_menu_gallery),
        Ejercicio(14, "Press Barra Smith", R.drawable.ic_menu_gallery),
        Ejercicio(15, "Peck Deck", R.drawable.ic_menu_gallery),

        // ESPALDA
        Ejercicio(16, "Peso Muerto", R.drawable.ic_menu_gallery),
        Ejercicio(17, "Dominadas", R.drawable.ic_menu_gallery),
        Ejercicio(18, "Remo con Barra", R.drawable.ic_menu_gallery),
        Ejercicio(19, "Remo con Mancuerna", R.drawable.ic_menu_gallery),
        Ejercicio(20, "Jalón al Pecho", R.drawable.ic_menu_gallery),
        Ejercicio(21, "Jalón Tras Nuca", R.drawable.ic_menu_gallery),
        Ejercicio(22, "Remo en Polea", R.drawable.ic_menu_gallery),
        Ejercicio(23, "Pull Over Polea", R.drawable.ic_menu_gallery),
        Ejercicio(24, "Peso Muerto Rumano", R.drawable.ic_menu_gallery),
        Ejercicio(25, "Hiperextensiones", R.drawable.ic_menu_gallery),
        Ejercicio(26, "Remo en T", R.drawable.ic_menu_gallery),
        Ejercicio(27, "Face Pull", R.drawable.ic_menu_gallery),
        Ejercicio(28, "Remo Invertido", R.drawable.ic_menu_gallery),
        Ejercicio(29, "Encogimientos Barra", R.drawable.ic_menu_gallery),
        Ejercicio(30, "Encogimientos Mancuernas", R.drawable.ic_menu_gallery),

        // PIERNAS
        Ejercicio(31, "Sentadilla", R.drawable.ic_menu_gallery),
        Ejercicio(32, "Sentadilla Frontal", R.drawable.ic_menu_gallery),
        Ejercicio(33, "Sentadilla Búlgara", R.drawable.ic_menu_gallery),
        Ejercicio(34, "Prensa", R.drawable.ic_menu_gallery),
        Ejercicio(35, "Zancadas Barra", R.drawable.ic_menu_gallery),
        Ejercicio(36, "Zancadas Mancuernas", R.drawable.ic_menu_gallery),
        Ejercicio(37, "Extensión Cuádriceps", R.drawable.ic_menu_gallery),
        Ejercicio(38, "Curl Femoral", R.drawable.ic_menu_gallery),
        Ejercicio(39, "Curl Femoral Sentado", R.drawable.ic_menu_gallery),
        Ejercicio(40, "Peso Muerto Piernas Rígidas", R.drawable.ic_menu_gallery),
        Ejercicio(41, "Hip Thrust", R.drawable.ic_menu_gallery),
        Ejercicio(42, "Gemelos Parado", R.drawable.ic_menu_gallery),
        Ejercicio(43, "Gemelos Sentado", R.drawable.ic_menu_gallery),
        Ejercicio(44, "Hack Squat", R.drawable.ic_menu_gallery),
        Ejercicio(45, "Step Ups", R.drawable.ic_menu_gallery),
        Ejercicio(46, "Abducción Cadera", R.drawable.ic_menu_gallery),
        Ejercicio(47, "Aducción Cadera", R.drawable.ic_menu_gallery),
        Ejercicio(48, "Sentadilla Sumo", R.drawable.ic_menu_gallery),
        Ejercicio(49, "Pistol Squat", R.drawable.ic_menu_gallery),
        Ejercicio(50, "Box Jumps", R.drawable.ic_menu_gallery),

        // HOMBROS
        Ejercicio(51, "Press Militar", R.drawable.ic_menu_gallery),
        Ejercicio(52, "Press Arnold", R.drawable.ic_menu_gallery),
        Ejercicio(53, "Elevaciones Laterales", R.drawable.ic_menu_gallery),
        Ejercicio(54, "Elevaciones Frontales", R.drawable.ic_menu_gallery),
        Ejercicio(55, "Pájaros", R.drawable.ic_menu_gallery),
        Ejercicio(56, "Press Mancuernas", R.drawable.ic_menu_gallery),
        Ejercicio(57, "Remo al Cuello", R.drawable.ic_menu_gallery),
        Ejercicio(58, "Elevaciones Polea", R.drawable.ic_menu_gallery),
        Ejercicio(59, "Press Tras Nuca", R.drawable.ic_menu_gallery),
        Ejercicio(60, "Face Pull Deltoide", R.drawable.ic_menu_gallery),
        Ejercicio(61, "Elevaciones Cruz", R.drawable.ic_menu_gallery),
        Ejercicio(62, "Press Landmine", R.drawable.ic_menu_gallery),
        Ejercicio(63, "Elevaciones Disco", R.drawable.ic_menu_gallery),
        Ejercicio(64, "Press Kettlebell", R.drawable.ic_menu_gallery),
        Ejercicio(65, "Handstand Push Ups", R.drawable.ic_menu_gallery),

        // BRAZOS
        Ejercicio(66, "Curl Barra", R.drawable.ic_menu_gallery),
        Ejercicio(67, "Curl Mancuernas", R.drawable.ic_menu_gallery),
        Ejercicio(68, "Curl Martillo", R.drawable.ic_menu_gallery),
        Ejercicio(69, "Curl Predicador", R.drawable.ic_menu_gallery),
        Ejercicio(70, "Curl Concentrado", R.drawable.ic_menu_gallery),
        Ejercicio(71, "Press Francés", R.drawable.ic_menu_gallery),
        Ejercicio(72, "Extensiones Tríceps", R.drawable.ic_menu_gallery),
        Ejercicio(73, "Fondos Tríceps", R.drawable.ic_menu_gallery),
        Ejercicio(74, "Patada Tríceps", R.drawable.ic_menu_gallery),
        Ejercicio(75, "Press Cerrado", R.drawable.ic_menu_gallery),
        Ejercicio(76, "Curl Polea Baja", R.drawable.ic_menu_gallery),
        Ejercicio(77, "Curl Polea Alta", R.drawable.ic_menu_gallery),
        Ejercicio(78, "Extensión Polea", R.drawable.ic_menu_gallery),
        Ejercicio(79, "Curl 21s", R.drawable.ic_menu_gallery),
        Ejercicio(80, "Curl Invertido", R.drawable.ic_menu_gallery),
        Ejercicio(81, "Tríceps Cuerda", R.drawable.ic_menu_gallery),
        Ejercicio(82, "Curl Spider", R.drawable.ic_menu_gallery),
        Ejercicio(83, "Extensión Overhead", R.drawable.ic_menu_gallery),
        Ejercicio(84, "Curl Zottman", R.drawable.ic_menu_gallery),
        Ejercicio(85, "Diamond Push Ups", R.drawable.ic_menu_gallery),

        // ABDOMEN
        Ejercicio(86, "Crunch", R.drawable.ic_menu_gallery),
        Ejercicio(87, "Plancha", R.drawable.ic_menu_gallery),
        Ejercicio(88, "Elevaciones Pierna", R.drawable.ic_menu_gallery),
        Ejercicio(89, "Bicicleta", R.drawable.ic_menu_gallery),
        Ejercicio(90, "Russian Twist", R.drawable.ic_menu_gallery),
        Ejercicio(91, "Mountain Climbers", R.drawable.ic_menu_gallery),
        Ejercicio(92, "Ab Wheel", R.drawable.ic_menu_gallery),
        Ejercicio(93, "V-Ups", R.drawable.ic_menu_gallery),
        Ejercicio(94, "Plancha Lateral", R.drawable.ic_menu_gallery),
        Ejercicio(95, "Dead Bug", R.drawable.ic_menu_gallery),

        // FUNCIONALES
        Ejercicio(96, "Burpees", R.drawable.ic_menu_gallery),
        Ejercicio(97, "Thrusters", R.drawable.ic_menu_gallery),
        Ejercicio(98, "Wall Balls", R.drawable.ic_menu_gallery),
        Ejercicio(99, "Kettlebell Swing", R.drawable.ic_menu_gallery),
        Ejercicio(100, "Turkish Get Up", R.drawable.ic_menu_gallery),
        Ejercicio(101, "Clean and Jerk", R.drawable.ic_menu_gallery),
        Ejercicio(102, "Snatch", R.drawable.ic_menu_gallery),
        Ejercicio(103, "Power Clean", R.drawable.ic_menu_gallery),
        Ejercicio(104, "Box Jumps", R.drawable.ic_menu_gallery),
        Ejercicio(105, "Battle Ropes", R.drawable.ic_menu_gallery),
        Ejercicio(106, "Farmers Walk", R.drawable.ic_menu_gallery),
        Ejercicio(107, "Sled Push", R.drawable.ic_menu_gallery),
        Ejercicio(108, "Tire Flip", R.drawable.ic_menu_gallery),
        Ejercicio(109, "Rope Climbs", R.drawable.ic_menu_gallery),
        Ejercicio(110, "Double Unders", R.drawable.ic_menu_gallery)
    )
}